#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.226.41.95
    HostName 54.226.41.95
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
